version: '1'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    depends_on:
      - mysql
  project-hibernate-final:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis